name: Send GitHub Trending Repositories Daily

on:
   schedule:
    - cron: "31 1 * * *"
   workflow_dispatch:
 

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 deep-translator yagmail PyEmail

    - name: Debug file existence
      run: |
        echo "Checking if send_moons_trends.py exists"
        ls -la  # 查看当前目录下的文件，确保 send_moons_trends.py 存在

    - name: Run the GitHub trending script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "Running send_github_trending.py"
        python send_github_trending.py

    - name: Run the Moons trends script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "Running send_moons_trends.py"
        python send_moons_trends.py  # 确保路径正确，或者指定绝对路径
        
    - name: Run the Moons trends script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "Running send_weekly_trends.py"
        python send_weekly_trends.py  # 确保路径正确，或者指定绝对路径
        
